-- ============================================================
-- GymBud: Supabase Storage Buckets & RLS Policies
-- Migration: 002_storage_buckets
-- ============================================================
-- Run this in the Supabase SQL Editor AFTER the main schema.
--
-- This creates three private storage buckets and locks them
-- down with RLS so users can only upload/read files in their
-- own folder: {bucket}/{user_id}/...
-- ============================================================


-- ============================================================
-- 1. CREATE STORAGE BUCKETS
-- ============================================================
-- These are private buckets (public = FALSE).
-- File access requires either:
--   a) A signed URL (generated by the backend)
--   b) A valid JWT where auth.uid() matches the folder path

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES
  (
    'onboarding-photos',
    'onboarding-photos',
    FALSE,
    5242880,                                    -- 5 MB max
    ARRAY['image/jpeg', 'image/png', 'image/webp']
  ),
  (
    'fitcheck-photos',
    'fitcheck-photos',
    FALSE,
    5242880,
    ARRAY['image/jpeg', 'image/png', 'image/webp']
  ),
  (
    'food-photos',
    'food-photos',
    FALSE,
    5242880,
    ARRAY['image/jpeg', 'image/png', 'image/webp']
  )
ON CONFLICT (id) DO NOTHING;


-- ============================================================
-- 2. ONBOARDING PHOTOS — RLS Policies
-- ============================================================
-- Storage path convention: onboarding-photos/{user_id}/{subfolder}/{filename}
-- `storage.foldername(name)` returns an array of path segments.
-- We check that the FIRST segment matches auth.uid().

CREATE POLICY "Users can upload their own onboarding photos"
  ON storage.objects FOR INSERT
  TO authenticated
  WITH CHECK (
    bucket_id = 'onboarding-photos'
    AND (storage.foldername(name))[1] = auth.uid()::TEXT
  );

CREATE POLICY "Users can view their own onboarding photos"
  ON storage.objects FOR SELECT
  TO authenticated
  USING (
    bucket_id = 'onboarding-photos'
    AND (storage.foldername(name))[1] = auth.uid()::TEXT
  );

CREATE POLICY "Users can update their own onboarding photos"
  ON storage.objects FOR UPDATE
  TO authenticated
  USING (
    bucket_id = 'onboarding-photos'
    AND (storage.foldername(name))[1] = auth.uid()::TEXT
  );

CREATE POLICY "Users can delete their own onboarding photos"
  ON storage.objects FOR DELETE
  TO authenticated
  USING (
    bucket_id = 'onboarding-photos'
    AND (storage.foldername(name))[1] = auth.uid()::TEXT
  );


-- ============================================================
-- 3. FITCHECK PHOTOS — RLS Policies
-- ============================================================
-- Same pattern: fitcheck-photos/{user_id}/{date}/{filename}

CREATE POLICY "Users can upload their own fitcheck photos"
  ON storage.objects FOR INSERT
  TO authenticated
  WITH CHECK (
    bucket_id = 'fitcheck-photos'
    AND (storage.foldername(name))[1] = auth.uid()::TEXT
  );

CREATE POLICY "Users can view their own fitcheck photos"
  ON storage.objects FOR SELECT
  TO authenticated
  USING (
    bucket_id = 'fitcheck-photos'
    AND (storage.foldername(name))[1] = auth.uid()::TEXT
  );

CREATE POLICY "Users can update their own fitcheck photos"
  ON storage.objects FOR UPDATE
  TO authenticated
  USING (
    bucket_id = 'fitcheck-photos'
    AND (storage.foldername(name))[1] = auth.uid()::TEXT
  );

CREATE POLICY "Users can delete their own fitcheck photos"
  ON storage.objects FOR DELETE
  TO authenticated
  USING (
    bucket_id = 'fitcheck-photos'
    AND (storage.foldername(name))[1] = auth.uid()::TEXT
  );


-- ============================================================
-- 4. FOOD PHOTOS — RLS Policies
-- ============================================================
-- Same pattern: food-photos/{user_id}/{filename}

CREATE POLICY "Users can upload their own food photos"
  ON storage.objects FOR INSERT
  TO authenticated
  WITH CHECK (
    bucket_id = 'food-photos'
    AND (storage.foldername(name))[1] = auth.uid()::TEXT
  );

CREATE POLICY "Users can view their own food photos"
  ON storage.objects FOR SELECT
  TO authenticated
  USING (
    bucket_id = 'food-photos'
    AND (storage.foldername(name))[1] = auth.uid()::TEXT
  );

CREATE POLICY "Users can update their own food photos"
  ON storage.objects FOR UPDATE
  TO authenticated
  USING (
    bucket_id = 'food-photos'
    AND (storage.foldername(name))[1] = auth.uid()::TEXT
  );

CREATE POLICY "Users can delete their own food photos"
  ON storage.objects FOR DELETE
  TO authenticated
  USING (
    bucket_id = 'food-photos'
    AND (storage.foldername(name))[1] = auth.uid()::TEXT
  );
